<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="MSI" failures="1" tests="2" name="ListenerTest2" time="0.012" errors="0" timestamp="2023-10-12T11:36:57 PDT">
  <testcase classname="ListenersTestng.ITestListener" name="test3" time="0.007">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at ListenersTestng.ITestListener.test3(ITestListener.java:20)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
at java.base/java.lang.Thread.run(Thread.java:833)
... Removed 12 stack frames]]>
    </failure>
  </testcase> <!-- test3 -->
  <testcase classname="ListenersTestng.ITestListener" name="test4" time="0.0"/>
  <testcase classname="ListenersTestng.ITestListener" name="test1" time="0.0">
    <ignored/>
  </testcase> <!-- test1 -->
  <testcase classname="ListenersTestng.ITestListener" name="test2" time="0.0">
    <ignored/>
  </testcase> <!-- test2 -->
</testsuite> <!-- ListenerTest2 -->
